services:
  - type: web
    name: hype-analyzer
    env: python
    buildCommand: "pip install -r requirements.txt && python -m nltk.downloader stopwords"
    startCommand: "gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: YOUTUBE_API_KEY
        sync: false # Requires manual entry in Render dashboard
      - key: GEMINI_API_KEY
        sync: false # Requires manual entry in Render dashboard
      - key: RENDER_DISK_PATH
        value: /data
    disk:
      name: hype-db-data
      mountPath: /data
      sizeGB: 1
